architecture: replication
auth:
  rootPassword: "123456"
  username: space
  password: "123456"
primary:
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 256Mi
secondary:
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 256Mi