# 集群名
clusterName: "cluster-space"

broker:
  # 1个 master 节点，每个 master 具有1个副节点，共6个 broker 节点
  size:
    master: 1
    replica: 1

  persistence:
    enabled: true
    size: 5Gi

  # 主节点资源分配
  master:
    brokerRole: ASYNC_MASTER
    jvmMemory: "-Xms512m -Xmx512m"
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi

  # 副节点资源分配
  replica:
    jvmMemory: "-Xms512m -Xmx512m"
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi

nameserver:
  replicaCount: 1

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 500Mi

dashboard:
  enabled: true
  replicaCount: 1

  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: rocketmq.space.org
    tls: []