# 集群名
clusterName: "cluster-space"

broker:
  # 1个 master 节点，每个 master 具有1个副节点，共6个 broker 节点
  size:
    master: 1
    replica: 1

  persistence:
    enabled: true
    size: 5Gi

  # 主节点资源分配
  master:
    brokerRole: ASYNC_MASTER
    jvmMemory: "-Xms128m -Xmx128m"
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi

  # 副节点资源分配
  replica:
    jvmMemory: "-Xms128m -Xmx128m"
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi

nameserver:
  replicaCount: 1

  resources:
    limits:
      cpu: 100
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 128Mi

dashboard:
  enabled: true
  replicaCount: 1

  ingress:
    enabled: true
    hosts:
      - host: rocketmq.space.org
    tls: []