replicaCount: 1

database:
  url: mysql-master-headless
  user: root
  password: "123456"
  db: xxl_job

ingress:
  enabled: true
  hosts:
    - host: xxl-job.space.org
      paths:
        - path: /
          pathType: ImplementationSpecific
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi