replicaCount: 1

database:
  url: mysql-master-headless
  user: root
  password: "123456"
  db: xxl_job

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: xxl-job.space.org
      paths:
        - path: /xxl-job-admin
          pathType: ImplementationSpecific
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

